#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)

pnpm format
pnpm lint:fix
pnpm generate

if [ -n "$STAGED_FILES" ]; then
  echo "$STAGED_FILES" | xargs git add
fi

git add packages/api-types/src/index.ts
