#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)

pnpm format
pnpm lint:fix
pnpm generate

if [ -n "$STAGED_FILES" ]; then
  echo "$STAGED_FILES" | xargs git add
fi

CONTROLLER_CHANGES=$(git diff --cached --name-only --diff-filter=ACMR -- api/src/main/java/com/universe/backend/controllers)

if [ -n "$CONTROLLER_CHANGES" ]; then
  git add packages/api-types/src/index.ts
else
  git checkout -- packages/api-types/src/index.ts
fi
